### PR TITLE
LPS-96623

### PR DESCRIPTION
**Pull request by yuhai**
@slnn, please help test the fix, and it will reduce the "update MBMessage set..." sql. Thanks.

cc @dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:messageboards

**Comment by slnn** [comment]
Here are test results for MB on qa env:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | DB CPU Usage (%) | Portal CPU Usage(%)
-- | -- | -- | -- | -- | -- | --
BaseLine | 4f0ab9eb | 8273 | 175 | 307 | 20,24,27 | 93,94,92
PR-417 | - | 8091 | 180 | 305 | 19,22,25 | 94,93,92

Regards
Lily

**Comment by yuhai** [comment]
Thanks @slnn

**Comment by yuhai** [comment]
send it to Tina to review.
https://github.com/tinatian/liferay-portal/pull/1411

**Pull request closed without merging**
