### PR TITLE
LPS-108376 Mark content layouts as approved and published to make them visible in the menu

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hey Lily, could you please launch the Fragment pages test again with this PR?
Thanks!

**Comment by slnn** [comment]
The fix of SampleSQLBuilder in this pull worked well, please see the screenshot.

Will run test with fragment compared with the normal basic web content.

PR-472

**Comment by slnn** [comment]
Hi @pavel-savinov 

With this pull, it only changes about the SampleSQLBuilder, do you have any other pulls to compare the improvement of fragment's performance? I'm running baseline for fragment now.

Lily

**Comment by slnn** [comment]
Test result be updated in the google doc

**Comment by dantewang** [comment]
@pavel-savinov 10% increase compared to baseline (web content on ordinary page)

**Pull request closed without merging**
