### PR TITLE
LPS-97259 Skip PortalCache for the full list of Soy template resources as cache key to avoid massive hash calculation

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:blogs

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn Please run on both main env and QA env.

**Comment by dantewang** [comment]
ci:test:blogs

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Here are test results on qa env, about 5.4%improvement on session cout

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 9edfcf6 | 5625 | 117 | 374
PR-423 | - | 5930 | 95.4 | 322

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
