### PR TITLE
LPS-84316

### PR DESCRIPTION
**Pull request by yuhai**
Hi @slnn 

Please help test the PR to check if the fix can cause performance decline.

Thanks,
Hai

### CODE REVIEW

**Comment by slnn** [comment]
OK, will update test results as I got them.

**Comment by slnn** [comment]
ci:test

**Comment by yuhai** [comment]
ci:stop

**Comment by yuhai** [comment]
ci:test

**Comment by slnn** [comment]
Hi @yuhai 
Here are test results, I can see a slight drop on session count on MessageBoard (-2.7%), AssetPublisher(-2.7%), Login(-2.7%/-1.4%)

Login | Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Log Out
-- | -- | -- | -- | -- | --
  | BaseLIne | 4436d9d | 17270 | 216 | 52.9
  | PR-328 | - | 16797 | 216 | 51.5
  | PR-328 | - | 17020 | 198 | 46.9


Web Content | Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of View Page
-- | -- | -- | -- | -- | --
  | BaseLIne | 4436d9d | 22301 | 369 | 136
  | PR-328 | - | 22566 | 382 | 141


MessageBoard | Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Add MB Thread
-- | -- | -- | -- | -- | --
  | BaseLIne | 4436d9d | 8529 | 165 | 298
  | PR-328 | - | 8292 | 207 | 328


Blog | Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Add Blog Entry
-- | -- | -- | -- | -- | --
  | BaseLIne | 4436d9d | 4840 | 167 | 515
  | PR-328 | - | 4869 | 154 | 494


DocumentLibrary | Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Add DL File
-- | -- | -- | -- | -- | --
  | BaseLIne | 4436d9d | 10001 | 534 | 732
  | PR-328 | - | 9860 | 782 | 950


Wiki | Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of Add Wiki Page
-- | -- | -- | -- | -- | --
  | BaseLIne | 4436d9d | 6125 | 180 | 569
  | PR-328 | - | 6193 | 208 | 593

AssetPublisher | Portal Version | Git Id | Session Count | MeanTime of Login | MeanTime of View Page With Filter
-- | -- | -- | -- | -- | --
  | BaseLIne | 4436d9d | 9248 | 201 | 141
  | PR-328 | - | 8997 | 199 | 142



cc @dantewang

**Comment by slnn** [comment]
Upload the cpu tracing for blog in nas-1/temp/lily.chi/2018-9-20-pr-328-Blog-cpu-tracing/cpu-tracing/

**Pull request closed without merging**
