### PR TITLE
LPS-106669 Update Freemarker to 2.3.29

### PR DESCRIPTION
**Pull request by dantewang**
@slnn Please run benchmark tests on all test cases.

cc @Preston-Crary In this pull I removed the patch for LPS-71553. The reason is that 2.3.29 no longer uses PropertyDescriptor; instead, a pojo named `FastPropertyDescriptor` is used. So I think we'll no longer hit `PropertyDescriptor.hashCode()` with 2.3.29. Please let me know if my understanding is wrong, thanks!

cc @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by slnn** [comment]
OK, got it and will update test results when I got them

**Comment by dantewang** [comment]
@vicnate5 Could you take a look at the CI results? Thanks!

Liferay Continuous Integration <notifications@github.com> 于 2020年2月14日周五
19:28写道：

**Comment by vicnate5** [comment]
@dantewang Test results look good.

**Comment by slnn** [comment]
Hi @dantewang 

Here are test results:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 15767 | 239 | 57.3 | -
PR | - | 16087 | 224 | 52 | 2.029555401

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 20271 | 348 | 130 | -
PR | - | 20672 | 349 | 129 | 1.978195452

MessageBoard:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 8845 | 167 | 268 | -
PR | - | 8811 | 172 | 273 | -0.384397965

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 5867 | 105 | 305 | -
PR | - | 5818 | 111 | 324 | -0.8351798193

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 9270 | 201 | 446 | -
PR | - | 9651 | 175 | 391 | 4.110032362

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 5361 | 200 | 557 | -
PR | - | 5462 | 200 | 547 | 1.88397687

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | b8495cee | 9381 | 217 | 133 | -
PR | - | 9331 | 211 | 135 | -0.5329922183


Regards
Lily

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8906

**Comment by slnn** [comment]
Hi @dantewang ,

Here are rerun test results on main env:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 8bc1b2f | 44091 | 268 | 80.3 | -
PR | - | 44809 | 263 | 78.6 | 1.628450251

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 8bc1b2f | 55826 | 603 | 185 | -
PR | - | 56235 | 509 | 154 | 0.7326335399

MessageBoards:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 8bc1b2f | 17799 | 45.7 | 90 | -
PR | - | 17634 | 138 | 162 | -0.9270183718

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 8bc1b2f | 15232 | 79.7 | 166 | -
PR | - | 15248 | 68.4 | 157 | 0.1050420168


DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 8bc1b2f | 26386 | 209 | 275 | -
PR | - | 26479 | 166 | 240 | 0.3524596377

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 8bc1b2f | 15506 | 232 | 447 | -
PR | - | 15569 | 267 | 478 | 0.4062943377

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 8bc1b2f | 26400 | 423 | 174 | -
PR | - | 26432 | 427 | 176 | 0.1212121212

Regards
Lily

**Pull request closed without merging**
