### PR TITLE
LPS-x Cache instanceable portlet

### PR DESCRIPTION
**Pull request by tinatian**
Hi Lily,

Could you please run a diff on web content with my change here?

cc @dantewang

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:retest

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Hi Tina,

Here are test results for web content:

PortalVersion | Session Count | Mean Time of Login | Mean Time of View Page
------------ | ------------- | ------------- | ------------- 
BaseLine | 27778 | 298 | 107
https://github.com/slnn/liferay-portal/pull/198 | 28011 |291 |104

**Comment by tinatian** [comment]
Thanks Lily!

**Pull request closed without merging**
