### PR TITLE
LPS-83616 SF

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
Hi Lily, I've just fixed the issues you mentioned and tests for HSQL pass. Let me know if you need anything else from me to run the tests.
Thanks!

**Comment by slnn** [comment]
OK, I will check it, if no other problems, I will start to run the tests and update test results as I got them.

Thanks
Lily

**Comment by slnn** [comment]
Hi @pavel-savinov 

No data be shown in the content page like this with the data that generated by SampleSQLBuilder.
samplesqlbuilder-generated-db-origin

I do these changes:
1>Generated FragmentCollection for fragments and fixed the groupId of fragmentEntryModel to make the data avaliable 
2>Add the origin widget pages back as other benchmark test cases need them
3>Make generated data for Content Page optional as we did not need them during other test cases.

Please check my changes in: https://github.com/pavel-savinov/liferay-portal/pull/201

With my changes, the data be shown like:
**Asset-list:**
samplesqlbuilder-generated-db-asset-list-1

**Media-gallery:**
samplesqlbuilder-generated-db-media-gallery-2

**Site-map:**
samplesqlbuilder-generated-db-site-map-3

**web-content:**
samplesqlbuilder-generated-db-web-content-4

Could you check if the data be shown as you expected? If not, please fix SampleSQLBuilder.

Thanks
Lily

**Pull request closed without merging**
