### PR TITLE
COMMERCE-7342 Add benchmark properties to allow disabling/enabling commerce facet portlet

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-7342

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Please see https://github.com/dantewang/liferay-portal/pull/2100

**Pull request closed without merging**
