### PR TITLE
LPS-84416 Cache ModelFactory for every type that handleUnknownType method handles

### PR DESCRIPTION
**Pull request by dantewang**
@slnn Please at least run login, webcontent and DL

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2018年8月15日周三
12:31写道：

**Comment by slnn** [comment]
Test results for Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | 8e418b7 | 49148 | 281 | 85.9
PR-320 | - | 48011 | 292 | 86.2
PR-320 | - | 49092 | 282 | 86.4

**Pull request closed without merging**
