### PR TITLE
Elasticsearch 7 REST client

### PR DESCRIPTION
**Pull request by BryanEngler**
Hi Lily, could you please run the benchmark tests against the branch and let me know if there are any performance issues with it? Thank you 

https://issues.liferay.com/browse/LPS-88272

### CODE REVIEW

**Comment by slnn** [comment]
OK, got it.

**Comment by BryanEngler** [comment]
Thanks! And just to let you know, we want to try to commit this by tomorrow if everything looks good because we have a release in 2 weeks, so if you could run it as soon as possible it would be very helpful! Thanks again!

**Comment by slnn** [comment]
Hi @BryanEngler 

Here are test results, I can see about 3.8% and 6.7% session count drop on Wiki and AssetPublisher

I have double checked on Wiki and AssetPublisher, the regression still be here.

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | 04175ac | 15764 | 256 | 460
PR-446 | - | 15158 | 268 | 463
PR-446 | - | 15224 | 237 | 440

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of VIew Page with Filter
-- | -- | -- | -- | --
BaseLine | 04175ac | 28136 | 418 | 170
PR-446 | - | 26244 | 400 | 117
PR-446 | - | 26307 | 419 | 176

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | 04175ac | 48953 | 266 | 80.2
PR-446 | - | 49669 | 267 | 76.8

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 04175ac | 62880 | 461 | 147
PR-446 | - | 61895 | 554 | 186

MB:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | 04175ac | 17651 | 25 | 73.9
PR-446 | - | 17631 | 24.8 | 73.3

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 04175ac | 15264 | 59.8 | 146
PR-446 | - | 15020 | 240 | 287

DL:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File
-- | -- | -- | -- | --
BaseLine | 04175ac | 26783 | 216 | 299
PR-446 | - | 26016 | 176 | 274


Note:
Test config: set embeddedHttpPort=I"9201" in com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config to use the 9201 port, https://issues.liferay.com/browse/LPS-88272

Regards
Lily

**Comment by slnn** [comment]
Profiles for Wiki and AssetPublisher be uploaded in here: https://mega.nz/#F!azAAFYwY!oqebW3cJVgHIvKyZERzMPQ

**Comment by slnn** [comment]
Hi @BryanEngler 

I'm sorry for that the commet for test resutls is missing, so I reupdated here:

From test results, I can see about 3.4% and 6.5% session count drop on Wiki and AssetPublisher, I have double checked them and the regression still be here.

I have update the profiles for Wiki and AssetPublisher in my last comment, but reupdate in here:https://mega.nz/#F!azAAFYwY!oqebW3cJVgHIvKyZERzMPQ

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page
-- | -- | -- | -- | --
BaseLine | 04175ac | 15764 | 256 | 460
PR-446 | - | 15158 | 268 | 463
PR-446 | - | 15224 | 237 | 440


AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of VIew Page with Filter
-- | -- | -- | -- | --
BaseLine | 04175ac | 28136 | 418 | 170
PR-446 | - | 26244 | 400 | 117
PR-446 | - | 26307 | 419 | 176

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File
-- | -- | -- | -- | --
BaseLine | 04175ac | 26783 | 216 | 299
PR-446 | - | 26016 | 176 | 274

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | 04175ac | 48953 | 266 | 80.2
PR-446 | - | 49669 | 267 | 76.8

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 04175ac | 62880 | 461 | 147
PR-446 | - | 61895 | 554 | 186

MessageBoards:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | 04175ac | 17651 | 25 | 73.9
PR-446 | - | 17631 | 24.8 | 73.3

Blog:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 04175ac | 15264 | 59.8 | 146
PR-446 | - | 15020 | 240 | 287


Regards
Lily

**Pull request closed without merging**
