### PR TITLE
LPS-88432 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @slnn,
Could you please execute the performance tests for this pull?

I've noticed that in the past we have some problems with Asset Publisher and I want be sure that I'm not increasing the performance.

Thanks you very much!!

**Comment by slnn** [comment]
Got it, will update test results as I got them.

@ealonso

**Comment by slnn** [comment]
Hi @ealonso 

No noticeable performance regression appeared with AssetPublisher
Here are test results:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page With Filter
-- | -- | -- | -- | --
BaseLine | de949cf | 8610 | 101 | 147
https://github.com/slnn/liferay-portal/pull/337 | - | 8607 | 136 | 159

Thanks 
Lily

**Comment by ealonso** [comment]
Hey @slnn,

Thanks you very much!!!

**Pull request closed without merging**
