### PR TITLE
LPS-90257 Add dropdown menu to the User Personal Bar

### PR DESCRIPTION
**Pull request by pei-jung**
Hi Lily,

Can you run performance test on this? Hopefully this is the last one...

Thanks

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by slnn** [comment]
OK, will update test results when I got them.

**Comment by pei-jung** [comment]
ci:stop

**Comment by slnn** [comment]
Hi @pei-jung 

As the head of master has some other problems about building, with these problems, even though the build successed, the bundle seems have some other issues, so I check your fix in the origin baseline.

But ant all will be faile by compile error when I apply this pull base on this commit GitId:7785b56839ef6cb5ca966b152063bf1b805f18d3 which is the baseline that we used


> /home/repo/portal/modules/apps/sharing/sharing-web/src/main/java/com/liferay/sharing/web/internal/product/navigation/personal/menu/SharedAssetsPersonalMenuEntry.java:38: error: cannot find symbol
     [exec] 		return SharingPortletKeys.SHARED_ASSETS;
     [exec] 		                         ^
     [exec]   symbol:   variable SHARED_ASSETS
     [exec]   location: class SharingPortletKeys

**Comment by pei-jung** [comment]
Hi @slnn,

The `SharingPortletKeys.SHARED_WITH_ME` was renamed to `SharingPortletKeys.SHARED_ASSETS` a couple days ago. Please see https://github.com/liferay/liferay-portal/blame/master/modules/apps/sharing/sharing-web/src/main/java/com/liferay/sharing/web/internal/constants/SharingPortletKeys.java#L25-L26. This new key is not available on 7785b56839ef6cb5ca966b152063bf1b805f18d3, which causes the compile error if you rebase my changes on that git hash.

**Comment by slnn** [comment]
OK, thanks! 
I will use the old key when rebase your changes on the origin baseline git hash.

**Comment by pei-jung** [comment]
Thank you!

**Pull request closed without merging**
