### PR TITLE
Lps 85890 v2

### PR DESCRIPTION
**Pull request by hudakl**
Hi Lily,

As I understood of the discussion with Shuyang, the cause of the performance issue in case of LPS-85890 is that the query is not cached and it is executed a lot more than it is supposed to.
I turned on the logging for MySQL and checked how frequently it is executed with my original fix on the latest master. I found in the logs that after several refresh the query runs only once.

Could you please run the tests on this branch if the issue still present at the moment?

Thank you,
Laci

### CODE REVIEW

**Comment by slnn** [comment]
Got it, will test it and update test results when I got them.

**Comment by slnn** [comment]
Hi @hudakl,

Currently, we need reinstall OS for our servers for other case, so I will check this pull when servers are ready.

Sorry for the inconvenient!

Regards
Lily

**Comment by slnn** [comment]
Hi @hudakl,

Sorry for the late reply.

I stll reproduce the performance regression on this pull with current head of master on MessageBoards:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Drop of Session Count (%)
-- | -- | -- | -- | -- | --
BaseLine | b203820 | 7552 | 154 | 280 | -
PR-379 | - | 6960 | 62.6 | 173 | -7.838983051
PR-379 | - | 6713 | 56.1 | 162 | -11.10963983

From cpu tracing, the method MBMessageLocalServiceImpl.getLastThreadMessage(long threadId, int status) cost more cpu time and it will add more queries than before, the query statement as below:

> select mbmessagei0_.messageId as messageId471_, mbmessagei0_.uuid_ as uuid2_471_, mbmessagei0_.groupId as groupId471_, mbmessagei0_.companyId as companyId471_, mbmessagei0_.userId as userId471_, mbmessagei0_.userName as userName471_, mbmessagei0_.createDate as createDate471_, mbmessagei0_.modifiedDate as modified8_471_, mbmessagei0_.classNameId as classNam9_471_, mbmessagei0_.classPK as classPK471_, mbmessagei0_.categoryId as categoryId471_, mbmessagei0_.threadId as threadId471_, mbmessagei0_.rootMessageId as rootMes13_471_, mbmessagei0_.parentMessageId as parentM14_471_, mbmessagei0_.subject as subject471_, mbmessagei0_.body as body471_, mbmessagei0_.format as format471_, mbmessagei0_.anonymous as anonymous471_, mbmessagei0_.priority as priority471_, mbmessagei0_.allowPingbacks as allowPi20_471_, mbmessagei0_.answer as answer471_, mbmessagei0_.lastPublishDate as lastPub22_471_, mbmessagei0_.status as status471_, mbmessagei0_.statusByUserId as statusB24_471_, mbmessagei0_.statusByUserName as statusB25_471_, mbmessagei0_.statusDate as statusDate471_ from MBMessage mbmessagei0_ where (mbmessagei0_.threadId=? )AND(mbmessagei0_.status=? ) order by  mbmessagei0_.createDate ASC , mbmessagei0_.messageId ASC limit ?, ? <Open> 2209 7 293

After digging into it found that these additional queries appeared on test step View RecentPosts(it means only visit the recent posts in MessageBoards portlet) and test step View MB Category(it means only visit the category in MessageBoards portlet), both of them will list these MB Threads in the page. 

The problem is that when portal list MB Threads, portal will invoke the query to db for each MBThread on the page, for example, in our test, when view one of the category in MB, the page will list 20 MBThreads in the page, so portal will invoke the query 20 times, similar issue appeared on visiting the recent posts in MB.

For the cache, I think you are right the query appeared only one time when first visit it, but we still see so many queries in our test, because before test starting, we have generated 100000 users and 10000 MBThreads, all of these MBThreads be created by one user, test will choose users randomly to execute test steps, eventhough we have "warmup" datas before testing, the "warmup" can make sure that each of these users are not  the first time to visit portal during test, but it can not make sure that for each MBThread, all of these users are not the first time to visit.

Detail test results, cpu tracings and sql logs please see: [Results for pr 379](https://mega.nz/#F!kgkTnSSA!5KLd4SE1hGVoDZbtKCE02g)

Description for sql log:

Please go to this path /sql/final-log/ in the zip to check the sql log

- phase1.sql is corresponding to the test steps of "Home Page"; 
- phase2.sql is corresponding to the test steps of "Log In";
- phase3.sql is corresponding to the test steps of "View MBPage";
- phase4.sql is corresponding to the test steps of "View RecentPosts";
- phase5.sql is corresponding to the test steps of "View MBCategory";
- phase6.sql is corresponding to the test steps of "View MBThread ";
- phase7.sql is corresponding to the test steps of "View MBThread Editor";
- phase8.sql is corresponding to the test steps of "Add MBThread";
- phase9.sql is corresponding to the test steps of "Add Reply";
- phase10.sql is corresponding to the test steps of "Log Out";

Regards
Lily

**Comment by hudakl** [comment]
Hi Lily,

Thank you for the detailed description. Now, I realise what did I miss so far. I'm working on another version. That will still contain additional queries, as they are required for solving the issue, but hopefully a lot less.

Regards,
Laci

@slnn

**Pull request closed without merging**
