### PR TITLE
LPS-119985 asset | SF

### PR DESCRIPTION
**Pull request by dantewang**
@slnn Please verify my changes in case it breaks anything although the unit test passes. Pay special attention to 2e8b308ebee2a6fec30b64ea338b26611583c2cc -- maybe I shouldn't use ?? to do the check.

### CODE REVIEW

**Comment by slnn** [comment]
Hi @dantewang 

I have tested this pull locally, it works well on my side.


Thanks
Lily

**Comment by dantewang** [comment]
@slnn Just want to double confirm about the macro "insertAssetEntry". If I don't pass in the maps, will logic in `<#if _assetCategoryModelsMap??>` be executed? If they are not executed then I'll forward this to Tina. Otherwise we need to use a different condition.

**Comment by slnn** [comment]
Hi @dantewang 

I have checked the db of MB which will not pass the maps when invoking the macro "insertAssetEntry", no data be inserted to table "AssetEntryAssetCategoryRel" and "AssetEntries_AssetTags" which should be inserted data if pass the maps.

Lily

**Comment by slnn** [comment]
should not only use ?? to do the check, I fix it by checking if the map is empty

https://github.com/dantewang/liferay-portal/pull/1770

**Pull request closed without merging**
