### PR TITLE
LPS-111253 Fix code and accessibility improvement

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @slnn! This is a similar PR to the other ones we're testing...

Could you please run the `login` and `asset-publisher` tests on this one? 

Thanks!

### CODE REVIEW

**Comment by slnn** [comment]
Hi @jbalsas 

Here are test results on this pull, I can see about 3.35 % perforamcne regression on AssetPublisher

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Log Out | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 9c7c6a8 | 43802 | 267 | 80.3 | -
PR | - | 43689 | 270 | 80.7 | -0.2579790877


AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 9c7c6a8 | 25781 | 434 | 181 | -
PR | - | 24917 | 433 | 181 | -3.351305225

cc @ginsonren @dantewang @tinatian @shuyangzhou 

Regards
Lily

**Comment by jbalsas** [comment]
Thanks @slnn! It's curious that mean time didn't change in this case... it implies tags don't affect response times, just session count?

I'll send another PR modifying the class hierarchy to drop `IncludeTag` and resend both to hopefully one final test

**Comment by slnn** [comment]
Hi @jbalsas 

The session count is the performance score, finally, you can see a normal meantime but a lower session count, this is the result of Grinder automatic adjustment. The automatic adjustment means that if the meantime is bigger, Grinder will reduce pressure of portal, so finally we can see a smaller session count and normal meantime, it means that if portal keep same response time, the throughput is small than before.

Thanks 
Lily

**Comment by jbalsas** [comment]
Understood!! Thanks for the explanation!! 😍

**Pull request closed without merging**
