### PR TITLE
Lps 85890 v3

### PR DESCRIPTION
**Pull request by hudakl**
Hi Lily,

Followup of: https://github.com/slnn/liferay-portal/pull/379

I added my new changes to the fix. In theory, this approach uses the original logic and only runs the query when that returns an empty value.

Could you please run the performance test on this?

Thanks,
Laci

### CODE REVIEW

**Comment by slnn** [comment]
OK, will check it and update test results when I got them.

Regards
Lily

**Comment by slnn** [comment]
Hi @hudakl,

Here are test results for this pull on MessageBoards:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Drop of Session Count (%)
-- | -- | -- | -- | -- | --
BaseLine | bfef0f5 | 7512 | 173 | 288 | -
PR-382 | - | 7472 | 69.5 | 188 | -0.5324813632
PR-382 | - | 7485 | 166 | 274 | -0.3594249201

I have checked the cpu tracing, it reduced the query compared with https://github.com/slnn/liferay-portal/pull/379.

Detail test results and cpu tracings be uploaded in:https://mega.nz/#F!M8dxAYaC!S5p-1sE5LU-AV6D-kUxrpg

Thanks
Lily

**Comment by hudakl** [comment]
Hi Lily,

Thanks for running the tests. Does this mean the new version is OK?

Thanks,
Laci

@slnn

**Comment by slnn** [comment]
Yes, from test results, it worked well for me.

**Pull request closed without merging**
