### PR TITLE
COMMERCE-4186 Fixes

### PR DESCRIPTION
**Pull request by dsitu**

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:reevaluate:1257401_1625

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn Please review this, and send to me after that. Thanks!

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/2285

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
