### PR TITLE
LPS-104274 Create document only once for the processing and validation executions

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hey @slnn,

Could you please run the same fragment test with this Portal code and the same profiler options?
Thanks!

/cc @tinatian

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Test results and cpu tracing please see email.

**Pull request closed without merging**
