### PR TITLE
Wc test1 For our test cases, it will skip getDDMTemplates() executed

### PR DESCRIPTION
**Pull request by yuhai**
@slnn thanks.

@dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai Please create a sub-task under https://issues.liferay.com/browse/LPS-97018 and send the pull. I'll forward to WEM team.

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
