### PR TITLE
LPS-x entries checker 1

### PR DESCRIPTION
**Pull request by tinatian**
Hi @slnn ,
Please run a diff on DL, and do a cpu profile on this pull. Upload the detailed result and profiles once you have it.

cc @dantewang

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by slnn** [comment]
OK, got it and will update results and profiles when I got them.

Regards
Lily

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
No need to test this, I will close this.

Tina.

**Pull request closed without merging**
