### PR TITLE
LPS-X Avoid to use stream to save performance

### PR DESCRIPTION
**Pull request by slnn**
Hi @dantewang

When checking ScopedCSSVariablesTopHeadDynamicInclude, I see this one uses the stream API in a common path, as we know, the performance of stream is not so good, so I use a normal loop here. Not sure if it will bring noticeable improvement on Session Count

/cc @yuhai

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test

**Comment by dantewang** [comment]
I did the similar optimization in a previous PR sent to Ginson, and I didn't get any improvement on her end. Let's see if the result could be different on your env.

**Comment by slnn** [comment]
Hi @dantewang 

From cpu tracing, I can see this:

Before my change, the cpu time of com.liferay.frontend.token.definition.internal.frontend.css.variables.DefaultThemeScopedCSSVariablesProvider.getScopedCSSVariablesCollection(HttpServletRequest) DefaultThemeScopedCSSVariablesProvider.java is **446**.

Ａfter my change, the cpu time is **253**

**Comment by slnn** [comment]
I am running the login test on main2 env, also asked @GinsonRen to run a diff with same baseline on main1 and main3 env

**Pull request closed without merging**
