### PR TITLE
LPD 20946 5 30

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@slnn I need startup profile on
- Master: https://github.com/slnn/liferay-portal/pull/782/commits/237d81e5f404028bc8707bba2abe66df65c60435
- Previous Merged PR: https://github.com/slnn/liferay-portal/pull/782/commits/49b3f1e08ed729c46c1a83b53071198c515b78c5
- Fix 1: https://github.com/slnn/liferay-portal/pull/782/commits/15f65df7ad8092a668d83075632823bdee88687a
- Fix 2: https://github.com/slnn/liferay-portal/pull/782/commits/c4deeaef9a1f792e27ff90fef131e190b6039f34
- Fix 3: https://github.com/slnn/liferay-portal/pull/782/commits/945bce7a4bb4bb7b052b4303935059b8f2c5ec0e
- Fix 4: https://github.com/slnn/liferay-portal/pull/782/commits/0fb068b8f659baa3aede14246ee2924377122d68

**Comment by slnn** [comment]
|                             | Open count of SQL  | Count of Prepared Statement Query | Open count of Prepared Statement |
|-----------------------------|--------------------|-----------------------------------|----------------------------------|
| master(237d81e)             | 1140               | 96                                | 64                               |
| Previous-Merged-PR-49b3f1e  | 906                | 783                               | 522                              |
| LPD-20946-5-30-pr-782-Fix-1 | 905                | 102                               | 68                               |
| LPD-20946-5-30-pr-782-Fix-2 | 825                | 102                               | 68                               |
| LPD-20946-5-30-pr-782-Fix-3 | 771                | 102                               | 68                               |
| LPD-20946-5-30-pr-782-Fix-4 | 711                | 102                               | 68                               |


Profiles please see: https://drive.google.com/drive/folders/1eyt4Ipe19m5MMCJgEXSeajP-aIpRkueJ?usp=sharing

**Comment by dantewang** [comment]
@slnn Pushed a new commit https://github.com/slnn/liferay-portal/pull/782/commits/32e90282073bf6cd6307e175252d82858ee0ac49, call it Fix-5. Please also run a profile, and compare with master and Fix-4. Thanks!

**Comment by slnn** [comment]
Update for Fix-5

**Pull request closed without merging**
