### PR TITLE
Wiki service upgrade

### PR DESCRIPTION
**Pull request by Preston-Crary**
Hi @slnn,

Can you run this against wiki and let me know the difference in performance, it should be pretty big so you might need to adjust the grinder settings to see the full change.

Also, this includes a DataFactory change so it requires rebuilding the database.

Thanks!

### CODE REVIEW

**Comment by slnn** [comment]
OK, will test it and update test results as soon as possible.

Lily

**Comment by slnn** [comment]
Hi @Preston-Crary 

Here are test results for Wiki:
From test results I can see an obvious change with the DB CPU usage.

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page |DB CPU (%) |Portal CPU(%)
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
Base Line | 10019ac |7073|262|733|8|91
https://github.com/slnn/liferay-portal/pull/210 | -|7098|340|786|6|92

Regards
Lily

**Comment by Preston-Crary** [comment]
Thanks!

**Comment by Preston-Crary** [comment]
@slnn, do you still have the grinder logs from this? If you do, can you email them to me?

**Comment by slnn** [comment]
Please check email.

**Pull request closed without merging**
