### PR TITLE
LPS-144609 We should not use try with resources with the statement connection since it will close it

### PR DESCRIPTION
**Pull request by achaparro**
Hi @slnn,

I think the key point is here:
https://github.com/slnn/liferay-portal/pull/590/commits/ada2a1660e5e5db65f80d06e9bd3bb25a44d4c03#diff-661962c538fbd8d0680b5944df1154e4de03054684dc463a7f381a8145c6e1ccL621

We were closing the statement before we finish it. I haven't tested it, please test it and resend to liferay-upgrades to execute the tests there.

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:liferay-online

**Comment by slnn** [comment]
Hi @achaparro 

The fix worked well on my side, resed this pull to liferay-upgrades, please see https://github.com/liferay-upgrades/liferay-portal/pull/214

Thanks
Lily

**Comment by achaparro** [comment]
ci:reevaluate:1297401_1279

**Comment by achaparro** [comment]
Thanks @slnn !

**Pull request closed without merging**
