### PR TITLE
LPS-104545 Fragment test

### PR DESCRIPTION
**Pull request by tinatian**
Hi @slnn,
Please use this pull to generate sample data for fragment, and this pull for the script (https://github.com/slnn/liferay-benchmark-ee/pull/130) to run a diff with web content test case.

cc @dantewang @shuyangzhou @pavel-savinov

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
@slnn You may see the ClassNotFoundException generated by SampleSQLBuilder, you can revert the changes @dantewang made and also remove the commence.ftl from sample.ftl to avoid generation of any table for commerce.

Tina.

**Comment by slnn** [comment]
OK, got it.

**Comment by slnn** [comment]
Hi all,

Here are test results:


Test Case | Portal Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count drop (%)
-- | -- | -- | -- | -- | --
WebContent | 6439321 | 58093 | 516 | 156 | -
Fragment | 6439321 | 53793 | 568 | 213 | -7.4019245




Lily

**Comment by slnn** [comment]
Detailed test results and cpu tracings be uploaded in https://mega.nz/#F!MllWDKKS!HMBeAqu6qGY43hNLicHMgA

**Pull request closed without merging**
