### PR TITLE
LPS-91743 Deploy analytics-web on ant all

### PR DESCRIPTION
**Pull request by pedroqueiroz**
Hey @slnn , can you please run a performance regression on this?

Please, refer to https://github.com/shuyangzhou/liferay-portal/pull/7449.

cc. @marcellustavares

### CODE REVIEW

**Comment by slnn** [comment]
OK, will test it and update test results when I got them.

Regards
Lily

**Comment by marcellustavares** [comment]
Thanks @slnn!

**Comment by slnn** [comment]
Hi all,

Here are test results, no noticeable performance regression appeared .

 Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 6e1c89d | 15580 | 288 | 72.1 | -
PR-355 | - | 15918 | 269 | 66.3 | 2.16944801

Web Content:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 6e1c89d | 20660 | 414 | 156 |  
PR-355 | - | 20488 | 402 | 151 | -0.8325266215

MessageBoards:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 6e1c89d | 7646 | 140 | 301 |  
PR-355 | - | 7628 | 186 | 341 | -0.2354172116

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 6e1c89d | 4637 | 161 | 491 |  
PR-355 | - | 4657 | 182 | 516 | 0.4313133491

DocumentLibrary:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 6e1c89d | 8429 | 382 | 676 |  
PR-355 | - | 8422 | 243 | 562 | -0.08304662475

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 6e1c89d | 5383 | 727 | 828 |  
PR-355 | - | 5566 | 372 | 615 | 3.399591306

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of VIew Page with Filter | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 6e1c89d | 9148 | 127 | 152 |  
PR-355 | - | 8976 | 140 | 158 | -1.880192392
  |   |   |   |   |  


cc @shuyangzhou

**Comment by marcellustavares** [comment]
Thank @slnn, forwarded to BChan, https://github.com/brianchandotcom/liferay-portal/pull/69385

**Pull request closed without merging**
