### PR TITLE
LPS-112458 Inlines IconTag markup to speed up tag output

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @slnn! 

This is a resend of https://github.com/slnn/liferay-portal/pull/480 without the `icon!!` output trace 😭 

Please, could you run the tests again when you have the chance so we have a clean view of this?

Thanks so much! 🙏

### CODE REVIEW

**Comment by slnn** [comment]
Hi @jbalsas 

Here are test results:

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | dfcc23a | 14797 | 373 | 385 | -
PR-481 | - | 14704 | 527 | 453 | -0.6285057782

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | dfcc23a | 15177 | 269 | 454 | -
PR-481 | - | 15680 | 245 | 113 | 3.314225473

cc @dantewang @shuyangzhou
Thanks
Lily

**Comment by slnn** [comment]
Update wrong test results, will update later when I got them.

**Comment by jbalsas** [comment]
> Update wrong test results, will update later when I got them.

I was happy for a second 😂

**Comment by slnn** [comment]
Hi @jbalsas 

Here are test results for this pull:

Blog:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | dfcc23a | 14797 | 373 | 385 | -
PR-481 | - | 14273 | 867 | 582 | -3.541258363
PR-481 | - | 14911 | 321 | 350 | 0.7704264378

Wiki:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | dfcc23a | 15177 | 269 | 454 | -
PR-481 | - | 15390 | 243 | 461 | 1.403439415

cc @dantewang @tinatian @shuyangzhou

Regards
Lily

**Comment by jbalsas** [comment]
Thanks @slnn!

Do we know what's the reason for that big discrepancy in the first run of the Blogs test? Is it possible there's some issue that's giving us inflated numbers?

Based on these results I'm assuming this should be now safe-ish to send... but I still want to try some other things, so I'll be sending you another PR later today.

Thanks for all your help!!

**Comment by slnn** [comment]
Hi @jbalsas 

For the big discrepancy in the first run of the Blogs test, I think it means the performance of Blog is not stable, this issue often appeared with poor performance issue.

Thanks
Lily

**Pull request closed without merging**
