### PR TITLE
LPS-112458 Inlines IconTag markup to speed up tag output

### PR DESCRIPTION
**Pull request by jbalsas**
Followup from https://github.com/slnn/liferay-portal/pull/478.

This inlines `IconTag` inside `ButtonTag` to avoid the tag instantiation and dispatching. 

Can you please re-run the tests to see how this looks?

Prior results:

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | dfcc23a | 14797 | 373 | 385 | -
PR | - | 14327 | 1010 | 635 | -3.176319524
PR | - | 14274 | 1220 | 717 | -3.534500237

Wiki:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | dfcc23a | 15177 | 269 | 454 | -
PR | - | 15425 | 291 | 504 | 1.634051525

/cc @shuyangzhou, @david-truong

### CODE REVIEW

**Comment by slnn** [comment]
Hi @jbalsas 

During our test for Wiki and Blog, I can see so many output like this in catalina.out, finally, it made the file size of catalina.out to 50.5 MB in Wiki test, normally, it should be only 80.2KB

> _icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!
_icon!!!

Wiki test results, this pull work well with wiki

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | dfcc23a | 15177 | 269 | 454 | -
PR-480 | - | 15393 | 267 | 479 | 1.423206167

Test for Blog is on the way, will update result when I got it


Thanks
Lily

**Comment by slnn** [comment]
Hi @jbalsas 

So many output like "_icon!!!" appeared in Blog test, it made the file size of catalina.out to 120.6MB in Blog test, normally, the size should be only 80.2KB.

Blog test results, sitll a noticeable regression appeared:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | dfcc23a | 14797 | 373 | 385 | -
PR-480 | - | 14445 | 1650 | 1060 | -2.37886058
PR-480 | - | 14185 | 1770 | 1120 | -4.135973508

Thanks
Lily

**Comment by jbalsas** [comment]
Thanks @slnn, sorry I wasted your time with this one! :(

These results are actually worse than before... I've sent https://github.com/slnn/liferay-portal/pull/481 removing that output trace, see if that was causing issues in the measurements.

Would you mind running the tests again there when you have a chance?

Thanks!

**Comment by slnn** [comment]
Hi @jbalsas 

OK, will retest it with the new pull: https://github.com/slnn/liferay-portal/pull/481 and I will update test results as I got them

**Pull request closed without merging**
