### PR TITLE
LPS-104711 Message Boards Tabs Inoperative on Content Page

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-104711

Added [additional commit](https://github.com/slnn/liferay-portal/pull/469/commits/cbadaa3f77a4f2634afbfd4274b962bac6598a98) to enter condition when layout type is a "Content Page" since this is a content page issue. 

This is created in response to performance regression:

Portal Version | Git Id | Session Count | Mean Time (Login) | Mean Time (Logout)
-- | -- | -- | -- | --
Before-LPS-104711 | 108bf3f6 | 47957 | 255 | 76.4
On-LPS-104711 | 4ddecbd2 | 46050 | 272 | 81.8

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by knchau** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Will test it and update results when I got them,

**Comment by slnn** [comment]
Test results be updated in the email.


Thanks
Lily

**Pull request closed without merging**
