### PR TITLE
LPS-63391 Exclude optional module from deployment

### PR DESCRIPTION
**Pull request by adolfopa**
@slnn Sorry for the delay. Can you retest this new PR?

Thanks!

### CODE REVIEW

**Comment by slnn** [comment]
OK, I will retest it and update the test results as soon as possible.

Thanks

**Comment by slnn** [comment]
Hi @adolfopa ,

Could you send this PR to Brian?

Thanks

**Comment by adolfopa** [comment]
@slnn I already did, but forgot to CC you. Sorry!

**Comment by slnn** [comment]
That's OK 

Thanks

**Pull request closed without merging**
