### PR TITLE
Mb test 4

### PR DESCRIPTION
**Pull request by yuhai**
cc @dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by slnn** [comment]
OK, will update test results when I got them.

**Comment by slnn** [comment]
Here are test results on MB with qa env:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | DB CPU (%) | Portal CPU (%)
-- | -- | -- | -- | -- | -- | --
BaseLine | abe5266 | 7630 | 167 | 295 | 18,21,23 | 92,92,93
PR-399 | - | 7503 | 125 | 249 | 17,20,22 | 92,92,93
PR-399 | - | 7457 | 134 | 263 | 17,20,22 | 91,92,93

**Comment by yuhai** [comment]
thanks @slnn

**Pull request closed without merging**
