### PR TITLE
LPS-87108

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn can you rerun the cases that have lower numbers? Some are lower for
several hundred...

Lily Chi <notifications@github.com> 于 2018年12月12日周三 11:29写道：

**Comment by dantewang** [comment]
@slnn Web Content, Message Board, Blog

**Comment by dantewang** [comment]
ci:reopen

**Comment by slnn** [comment]
Here are rerun test results:

Web Content:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 7e87034 | 22028 | 379 | 143
https://github.com/slnn/liferay-portal/pull/336 | - | 21281 | 401 | 149
Rerun https://github.com/slnn/liferay-portal/pull/336 | - | 20661 | 373 | 141

Message Board:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | 7e87034 | 8244 | 223 | 337
https://github.com/slnn/liferay-portal/pull/336 | - | 8015 | 188 | 314
Rerun https://github.com/slnn/liferay-portal/pull/336 | - | 80852 | 228 | 347

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry
-- | -- | -- | -- | --
BaseLine | 7e87034 | 5103 | 118 | 395
https://github.com/slnn/liferay-portal/pull/336 | - | 4986 | 126 | 422
Rerun https://github.com/slnn/liferay-portal/pull/336 | - | 4882 | 141 | 449

**Pull request closed without merging**
