### PR TITLE
LPS-x open nlp

### PR DESCRIPTION
**Pull request by tinatian**
Hi Lily,
Please run a performance diff on login and DL with this pull.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by slnn** [comment]
OK, will check it and update test results when I got them.

**Comment by tinatian** [comment]
HI @slnn 
If you have not run this pull, then do not need to run it, run this pull instead: https://github.com/lanceji92674957/liferay-portal/pull/224.

If you already have a result for it, please update the result, and run another diff for the pull above.

Thanks.
Tina.

**Comment by slnn** [comment]
OK, got it.

**Pull request closed without merging**
