### PR TITLE
Lps 80949 3

### PR DESCRIPTION
**Pull request by shuyangzhou**
@ngriffin7a I think the apply to RuntimePageImpl.doProcessTemplate() for the header processing is going to cost us a lot.
@slnn please run some regression tests.

@ngriffin7a since we are not enabling portlet 3 in this release, we should try the best to not pay any performance penalty. I think we need a streamlined way to process headers and renders by a single shot, when we are really doing render. But first let's see how much it costs us.

### CODE REVIEW

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Here are test results:
Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Log Out
-- | -- | -- | -- | --
BaseLine | 4cbd19d | 17003 | 214 | 52.6
PR-302 | - | 17439 | 219 | 53.9

Web Content:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 4cbd19d | 23033 | 385 | 143
PR-302 | - | 22662 | 364 | 136


MessageBoard:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread
-- | -- | -- | -- | --
BaseLine | 4cbd19d | 8324 | 212 | 335
PR-302 | - | 8188 | 229 | 354

**Comment by ngriffin7a** [comment]
@slnn Thank you so much for the stats.

@shuyangzhou Perhaps the PR could be merged, but comment-out lines 422-476 of RuntimePageImpl.java for the 7.1 GA1 release? https://github.com/shuyangzhou/liferay-portal/blob/f2d8d2f145bc20a9e542067df2fb93ea2024b94b/portal-impl/src/com/liferay/portal/layoutconfiguration/util/RuntimePageImpl.java#L422-L476

**Comment by shuyangzhou** [comment]
@ngriffin7a can we really do that? If so, how do we generate the values for portletHeaderRequestMap ?
I think the right way is to merge the header and render generation logic, in case we are really doing the render.

**Comment by ngriffin7a** [comment]
@shuyangzhou The portletHeaderRequestMap can be an empty, non-null map. I agree that the performance can be increased but that is a refactor that can be postponed until after GA1.

**Comment by shuyangzhou** [comment]
@ngriffin7a ok, that's good enough. Can you send me back the pull with the removal of that section? Removal rather than comment, I don't think Brian will like a big chunk of commented code. Make sure the removal is clean enough and we just remember that commit on the ticket. Later when we revisit, just revert the removal commit.

**Comment by ngriffin7a** [comment]
@shuyangzhou OK will do!

**Comment by ngriffin7a** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6286

**Pull request closed without merging**
