### PR TITLE
[TS] Proposed Fix: LPS-78984 Performance Fix Testing

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-78984

Previous test run pr: https://github.com/slnn/liferay-portal/pull/269

Hi @slnn, 

Can you do a complete re-test for this test run?
Thanks!

### CODE REVIEW

**Comment by slnn** [comment]
OK, got it, will update test results as soon as possible.

**Comment by ericyanLr** [comment]
Thanks Lily!

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:test

**Pull request closed without merging**
