### PR TITLE
LPS 149061 3 16

### PR DESCRIPTION
**Pull request by dantewang**
@slnn Please view my changes, and clean up the commits, and resend. By the way, I'd like to see you put the JSONLocalizer change in a separate commit, and applying in a anohter.

### CODE REVIEW

**Comment by dantewang** [comment]
@slnn And this should bring a slightly higher result than your previous change, because I reduced most of the JSONObject -> Map copying during the deep copy.

@GinsonRen please run a diff. Thanks!

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test result? The semantic versioning error is known so you can ignore it.

**Comment by slnn** [comment]
Resend in https://github.com/dantewang/liferay-portal/pull/2190

**Comment by zhangyan0701** [comment]
Results of ci:test:relevant are unrelated. But there are too many failed jobs in ci:test:default, there might be Jenkins problems, so will check the results of https://github.com/liferay-core-infra/liferay-portal/pull/478.

**Pull request closed without merging**
