### PR TITLE
LPS-69436 Fix rebase errors

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @slnn,
I am sending you this PR to test if it produces some performance issues in portal.

You may remember we merged this in master some weeks ago and we had to revert it because of huge performance issues that this produced.

Let us know the results.
Thanks!

/cc @jbalsas @brunobasto

### CODE REVIEW

**Comment by slnn** [comment]
OK, I will test this pull and update test results as soon as possible.

Thanks
Lily

**Comment by ambrinchaudhary** [comment]
ci:reopen

**Comment by ambrinchaudhary** [comment]
ci:retest

**Comment by slnn** [comment]
Test results please see the email.

Thanks!
Lily

**Pull request closed without merging**
