### PR TITLE
Remove portal instances init company part 2

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:startup

**Comment by slnn** [comment]
Hi @zhangyan0701 

Could you help to check the results in this pull when you have time?

Thanks
Lily

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:startup

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
@slnn 

No regressions found.

**Comment by slnn** [comment]
> @slnn
> 
> No regressions found.

Thanks!

**Pull request closed without merging**
