### PR TITLE
LPS-82668 Cache the final ResourceBundleLoader

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test

**Comment by csierra** [comment]
ci:reopen

**Comment by slnn** [comment]
Will update test results as I got them.

Thanks
Lily

**Comment by slnn** [comment]
Detail test resutls please check the email, it fixed the regression.


Thanks
Lily

**Pull request closed without merging**
