### PR TITLE
LPS-96609

### PR DESCRIPTION
**Pull request by yuhai**
@slnn Compare with https://github.com/slnn/liferay-portal/pull/414, I did the change for the query result list. It might be same result with https://github.com/slnn/liferay-portal/pull/414. Thanks.

cc @dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:messageboards

**Comment by slnn** [comment]
Here are test  results for MB on qa env:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | DB CPU Usage (%) | Portal CPU Usage(%)
-- | -- | -- | -- | -- | -- | --
BaseLine | 7c6e55e | 8156 | 178 | 311 | 20,23,26 | 94,93,94
BaseLine | 7c6e55e | 8229 | 184 | 322 | 20,24,26 | 94,93,94
PR-416 | - | 7881 | 200 | 320 | 16,18,20 | 95,94,93
PR-416 | - | 8252 | 167 | 300 | 17,20,22 | 93,94,94



Lily

**Comment by yuhai** [comment]
thanks @slnn. Send it to Tina to review.
https://github.com/tinatian/liferay-portal/pull/1410

**Pull request closed without merging**
