### PR TITLE
LPS-92343 Error Template

### PR DESCRIPTION
**Pull request by tinatian**
Hi Lily,

Could you please keep an eye on the test result of this pull, if everything is fine, please run a diff on login and webconent.

cc @dantewang

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by slnn** [comment]
Hi Tina,

On the head of master, web content had this bug that a new and empty Web Content Dispaly portlet will be added to the page automaticly when publishing a basice web content in the Web Content Dispaly portlet, please see https://issues.liferay.com/browse/LPS-93494

I suspected LPS-93494 caused the failed of these smoke tests

Here are performance test results on Login and Web Content:

Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout
-- | -- | -- | -- | --
BaseLine | 3bf1a5f | 44259 | 293 | 88.4
PR | - | 43967 | 303 | 91.2
PR | - | 44123 | 304 | 91.3

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page
-- | -- | -- | -- | --
BaseLine | 3bf1a5f | 56260 | 675 | 228
PR | - | 56412 | 613 | 211
PR | - | 56426 | 615 | 213


Lily

**Comment by slnn** [comment]
ci:retest

**Comment by slnn** [comment]
Hi Tina,

I have checked all the test about mysql + tomcat, most errors appeared in upstream,  please see test resutls in testray:https://testray.liferay.com/home/-/testray/case_results/index?delta=200&p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=520884242

But these faileds seem that did not appear in upstream:

https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/305024
https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/284701
https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/284702
https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/295197/AXIS_VARIABLE=2,label_exp=!master/console

Lily

**Pull request closed without merging**
