### PR TITLE
LPS-112458 PERF_TEST Use clay:button-fast in ratings-taglib

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Lily! 

I agreed with @shuyangzhou to send this to you for a regression perf test.

In the past, a similar change caused:

> The commits of LPS-109393 in master caused about -6.8% performance regression on Blog and -3.4% on Wiki

Portal Version | Git Id | Session Count | Mean Time
-- | -- | -- | --
Login | Add Blog Entry
Before LPS-109393 | fd47167 | 15179 | 773 | 166
On LPS-109393 | b40de6d | 14148 | 1670 | 920

Portal Version | Git Id | Session Count | Mean Time
-- | -- | -- | --
Login | Add Wiki Page
Before LPS-109393 | fd47167 | 15478 | 232 | 446
On LPS-109393 | b40de6d | 14954 | 267 | 478

Based on this, the team decided to [Remove clay:button and use hardcoded markup](https://github.com/4lejandrito/liferay-portal/pull/460/files#diff-d920efc00933b1ceb739fc52680d1eb3)

This PR introduces a pure Java clay tag that should be safe and performant.

Could you please run both Blogs and Wiki tests on this to verify this is safe to apply?

Thanks!

/cc @adolfopa

### CODE REVIEW

**Comment by slnn** [comment]
Hi @jbalsas 

Here are test results on Blog and Wiki, this pull worked well with Wiki, but for Blog, I can still see noticeable performance regression eventhoug I have double run test with Blog.

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | dfcc23a | 14797 | 373 | 385 | -
PR | - | 14327 | 1010 | 635 | -3.176319524
PR | - | 14274 | 1220 | 717 | -3.534500237

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | dfcc23a | 15177 | 269 | 454 | -
PR | - | 15425 | 291 | 504 | 1.634051525



cc @shuyangzhou 

Regards
Lily

**Comment by jbalsas** [comment]
Hey @slnn, thanks for the report!

Is the performance loss acceptable?

This is just a pure Java tag... so not sure what else to do here... the only thing I can think of is that on [`IconTag::doStartTag()`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/IconTag.java#L41-L44) we do the following:

```java
ThemeDisplay themeDisplay = (ThemeDisplay)request.getAttribute(
	WebKeys.THEME_DISPLAY);

String pathThemeImages = themeDisplay.getPathThemeImages();
```

@shuyangzhou, @slnn, would you advice to do this elsewhere? As you can see the tag doesn't do much and basically just extends `IncludeTag` without even dispatching to a JSP... what other options do we have?

Thanks!

**Comment by jbalsas** [comment]
The other things that might add slowness are:
- [IconTag instantiation](https://github.com/slnn/liferay-portal/pull/478/commits/c553055ba4a9ad195276ad6c0f206c969ee50eee#diff-866073174dfe2360c5d72c8ae2965bebR260)
- [ResourceBundle resolution](https://github.com/slnn/liferay-portal/pull/478/commits/c553055ba4a9ad195276ad6c0f206c969ee50eee#diff-866073174dfe2360c5d72c8ae2965bebR272)

Maybe there's a better way to do either of those for this context?

**Comment by shuyangzhou** [comment]
The regression is too big to be acceptable. @slnn please generate the profiles, and @dantewang please do a round of investigation, should be something obvious for this big regression.

**Comment by slnn** [comment]
Upload the profiles for Blog in https://drive.google.com/drive/folders/1zMOnHQqo5kVvCb2leGVrMljHyxyaU4Lz?usp=sharing

Lily

**Comment by dantewang** [comment]
@jbalsas From the profile, the major overhead comes purely from tag processing, including the tag's css class processing (a relatively smaller part), the usage of `IconTag` (half of the `ButtonTag` processing), and the common overhead as a sub class of `BaseContainerTag -> IncludeTag`. `IconTag` itself is similar, for example, it also has the common overhead of being a `BaseContainerTag`.

The resource bundle processing is not the cause because in our test case (ratings taglib) there's no label.

The profile doesn't show any huge bottleneck. However, there's a big difference between Wiki and Blog. In Blogs test case, the Blogs portlet shows 10 blog posts per page, and each post will render a ratings tag; when we visit any post, the ratings tag will also be rendered. As a result, in Blogs test case, the ratings tag is hit with a much higher frequency than in Wiki test case. Small overhead can stack up much easier in Blogs into a big overhead.

**Comment by jbalsas** [comment]
Thanks @dantewang!

What would be your recommendation? What should we do?

**Comment by jbalsas** [comment]
Hey @slnn, @dantewang, I've inlined the `IconTag` instance to see where that takes us... can you please rerun tests at https://github.com/slnn/liferay-portal/pull/480?

Thanks!

**Pull request closed without merging**
