### PR TITLE
LPS-120376 use beanshell

### PR DESCRIPTION
**Pull request by dantewang**
@slnn Could you try this and fix any issue you see. This is attempting to replace your commit https://github.com/dantewang/liferay-portal/pull/1807/commits/82dc51f7a30521bc8b2948ef1a7bd18964fa76ff

### CODE REVIEW

**Comment by slnn** [comment]
Hi @dantewang 

The changes in this pull only handle the default properties file benchmarks.properties, it does not contain any logic about handle these customer property files such as benchmarks.${username}.properties, so you want use the bean shell script instead the task to handle them, right?

Lily

**Comment by dantewang** [comment]
@slnn This part does the magic:
```
for (String propertyKey : properties.stringPropertyNames()) {
	properties.setProperty(propertyKey, project.getProperty(propertyKey));
}
```
For every key from benchmarks.properties, replace the value from current ant project context. Please test whether property overriding is working with this pull.

**Comment by slnn** [comment]
I have tested this pull, it worked well when no custom property file exists, but the logic is wrong when apply custom property file, I am fixing this now.

**Comment by dantewang** [comment]
@slnn Shouldn't Ant context always have the correct property values? Anyway we should rely on what Ant context already has instead of implementing our own logic.

**Comment by slnn** [comment]
Resend in https://github.com/dantewang/liferay-portal/pull/1811

**Pull request closed without merging**
