### PR TITLE
Mb test 6

### PR DESCRIPTION
**Pull request by yuhai**
cc @dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
ci:stop

**Comment by yuhai** [comment]
ci:test:sf

**Comment by slnn** [comment]
Here are test results for MB on qa env:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | DB CPU (%) | Portal CPU (%)
-- | -- | -- | -- | -- | -- | --
BaseLine | db1f457 | 7496 | 104 | 226 | 16,20,22 | 92,93,93
BaseLine | db1f457 | 7701 | 175 | 300 | 18,21,24 | 92,93,93
PR-405 | - | 7184 | 69.6 | 184 | 16,18,21 | 87,90,91
PR-405 | - | 7581 | 212 | 322 | 18,20,23 | 93,94,93




Detailed test results and sql log please see //nas-1/temp/lily.chi/2019-5-performance-tuning/master/MB/2019-5-30-pr-405/

**Pull request closed without merging**
